/*
 * generated by Xtext 2.25.0
 */
package curvehtml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyHtmlRuntimeModule extends AbstractMyHtmlRuntimeModule {
}
