/*
 * generated by Xtext 2.25.0
 */
package curvehtml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyHtmlStandaloneSetup extends MyHtmlStandaloneSetupGenerated {

	public static void doSetup() {
		new MyHtmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
