/*
 * generated by Xtext 2.25.0
 */
package curvehtml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyHtmlUiModule extends AbstractMyHtmlUiModule {

	public MyHtmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
