/*
 * generated by Xtext 2.25.0
 */
package curvehtml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import curvehtml.MyHtmlRuntimeModule;
import curvehtml.MyHtmlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyHtmlIdeSetup extends MyHtmlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyHtmlRuntimeModule(), new MyHtmlIdeModule()));
	}
	
}
