/*
 * generated by Xtext 2.25.0
 */
package curvehtml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyHtmlScopeProvider extends DelegatingScopeProvider {
}
